# Generated by Django 6.0.3 on 2026-03-11 10:53

import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=32, verbose_name='stock code')),
                ('external_id', models.CharField(max_length=128, unique=True, verbose_name='external id')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('link', models.URLField(blank=True, default='', max_length=2048, verbose_name='link')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('summary', models.TextField(blank=True, default=None, null=True, verbose_name='summary')),
                ('useful', models.BooleanField(blank=True, default=None, null=True, verbose_name='useful')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['stock_code', 'useful', 'created_at'], name='news_news_stock_c_509923_idx')],
            },
            bases=(shared.models.StockNamedMixin, models.Model),
        ),
    ]
