# Generated by Django 6.0.3 on 2026-03-11 10:53

import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=32, null=True, verbose_name='stock code')),
                ('quantity', models.BigIntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='unit price')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='total amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'indexes': [models.Index(fields=['stock_code'], name='asset_asset_stock_c_bd2cfb_idx'), models.Index(fields=['stock_code', 'updated_at'], name='asset_asset_stock_c_c1e6d0_idx')],
            },
            bases=(shared.models.StockNamedMixin, models.Model),
        ),
    ]
