# Generated by Django 6.0.3 on 2026-03-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=6)),
                ('minute_at', models.DateTimeField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'ordering': ['minute_at'],
                'unique_together': {('stock_code', 'minute_at')},
            },
        ),
    ]
