# Generated by Django 6.0.3 on 2026-03-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutecandle',
            name='volume',
            field=models.BigIntegerField(),
        ),
    ]
