# Generated by Django 6.0.3 on 2026-03-11 10:53

import django.db.models.deletion
import django.utils.timezone
import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.TextField(verbose_name='request payload')),
                ('response_payload', models.TextField(verbose_name='response payload')),
                ('parsed_decision', models.JSONField(blank=True, default=dict, verbose_name='parsed decision')),
                ('processing_time_ms', models.IntegerField(default=0, verbose_name='processing time (ms)')),
                ('is_error', models.BooleanField(default=False, verbose_name='is error')),
                ('error_message', models.TextField(blank=True, default=None, null=True, verbose_name='error message')),
                ('result', models.CharField(choices=[('HOLD', 'Hold'), ('BUY', 'Buy'), ('SELL', 'Sell')], default='HOLD', max_length=16, verbose_name='result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'indexes': [models.Index(fields=['result'], name='trader_deci_result_c38f2a_idx'), models.Index(fields=['created_at'], name='trader_deci_created_44d03a_idx'), models.Index(fields=['is_error', 'created_at'], name='trader_deci_is_erro_85af18_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=32, verbose_name='stock code')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='order price')),
                ('order_quantity', models.BigIntegerField(verbose_name='order quantity')),
                ('order_total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='order total amount')),
                ('result_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='result price')),
                ('result_quantity', models.BigIntegerField(verbose_name='result quantity')),
                ('result_total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='result total amount')),
                ('order_placed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='order placed at')),
                ('result_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='result executed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('decision_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trader.decisionhistory', verbose_name='decision history')),
            ],
            options={
                'indexes': [models.Index(fields=['stock_code'], name='trader_orde_stock_c_77149e_idx'), models.Index(fields=['order_placed_at'], name='trader_orde_order_p_f3c847_idx'), models.Index(fields=['result_executed_at'], name='trader_orde_result__ed8408_idx'), models.Index(fields=['created_at'], name='trader_orde_created_5bae27_idx'), models.Index(fields=['stock_code', 'created_at'], name='trader_orde_stock_c_db1f2b_idx')],
            },
            bases=(shared.models.StockNamedMixin, models.Model),
        ),
    ]
